# Generated by Django 3.1.7 on 2021-04-02 22:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='date',
            field=models.DateTimeField(default=datetime.date(2000, 1, 1), verbose_name='date published'),
        ),
    ]
